-- Drop any existing data.

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS bookmark;
DROP TABLE IF EXISTS seq;
DROP VIEW IF EXISTS bookmarks;
DROP VIEW IF EXISTS categories;
DROP TRIGGER IF EXISTS add_user;
DROP TRIGGER IF EXISTS add_seq;
DROP TRIGGER IF EXISTS reorder;
